<?php 
$this->title = "My Clients"; 
$this->headTitle($this->title); 
?> 
<p><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'add'));?>">Add new Client</a></p> 
<table> 
<tr> 
    <th>Name</th> 
    <th>Organization</th>
    <th>Designation</th> 
    <th>Email</th>
    <th>Contact Number</th>  
     
</tr> 
<?php $t = 1; ?>
<?php foreach($this->clients as $client) : ?> 
<?php if($t%2 == 0 ){$class = "even";}else{$class = "odd";} $t++; ?>
<tr class="<?php echo $class ?>"> 
    <td><?php echo $this->escape($client->name);?></td> 
    <td><?php echo $this->escape($client->organization);?></td>
    <td><?php echo $this->escape($client->designation);?></td> 
    <td><?php echo $this->escape($client->email);?></td>
    <td><?php echo $this->escape($client->contact_no);?></td>
    <td id="links"> 
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'edit', 'id'=>$client->id));?>">Edit</a> 
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'delete', 'id'=>$client->id));?>">Delete</a> 
    </td> 
</tr> 
<?php endforeach; ?> 
</table> 
