<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); 
$this->headTitle()->setSeparator(' - '); 
$this->headTitle('Pyxis Admin'); 
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');
echo $this->doctype(); ?> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?> 
</head> 
<body> 
<div id="header"> <div id="logged-in-as">
<?php echo $this->loggedInAs(); ?> </div>
</div>
<div id="content"> 
    <h1><?php echo $this->escape($this->title); ?></h1> 
    <?php echo $this->layout()->content; ?> 
</div> 
 /*changes commited */
</body> 
</html>